# workflow name
name: Hexo Blog CI

# main branch on push, auto run
on: 
  push:
    branches:
      - main

env:
  TZ: Asia/Shanghai

jobs:
  build: 
    runs-on: windows-latest 
        
    steps:
    # check it to your workflow can access it
    # from: https://github.com/actions/checkout
    - name: Checkout Repository main branch
      uses: actions/checkout@main
      
    # from: https://github.com/actions/setup-node  
    - name: Setup Node.js 18.x 
      uses: actions/setup-node@main
      with:
        node-version: "18.x"

    - name: Setup Dependencies
      run: |
        node node_modules/puppeteer/install.js
        npm install hexo-cli -g
    #    npm install
    
    - name: Generate files
      # 编译 markdown 文件
      run: |
        hexo clean
        hexo generate

    - name: Deploy hexo blog
      # 将编译后的博客文件推送到指定仓库
      run: |
        cd ./public && git init && git add .
        git config --global user.name 'Yu-Qi-hang' 
        git config --global user.email '2659464450@qq.com'
        git add .
        git commit -m "GitHub Actions Auto Builder at $(date +'%Y-%m-%d %H:%M:%S')"
        git push -f --quiet "https://Yu-Qi-hang:${{ secrets.GITEE_PASSWORD }}@gitee.com/Yu-Qi-hang/yu-qi-hang.git" master:master

    - name: Update pages
      #自动更新Gitee Pages
      run: |
        cd ./git-update-pages
        echo "${{ secrets.GITEE_PASSWORD }}" > temp.json
        npm link
        git-update-pages
        rm temp.json